"use client";

import Link from "next/link";
import { SITE_CONTENT } from "./site-content";

export function ArticlesPageV2(){const topics=[["SCALING & CROISSANCE","Franchir un palier sans multiplier la complexité."],["OFFRES & POSITIONNEMENT","Créer une valeur claire, rare et difficile à comparer."],["VENTE & CONVERSION","Transformer la demande en décisions mesurables."],["SYSTÈMES & LEVIER","Construire ce qui continue de produire après l’effort."],["LEADERSHIP & DYNASTIE","Décider, gouverner et construire au-delà du revenu."]];return <><section className="resource-manifesto"><p className="eyebrow">ARTICLES & NEWSLETTER</p><h2>Des analyses pour penser comme un architecte.</h2><p>Chaque catégorie sera reliée à sa collection Substack dès que tu transmettras les liens définitifs.</p></section><section className="article-explorer">{topics.map((x,i)=><Link href={`/articles#categorie-${i+1}`} id={`categorie-${i+1}`} key={x[0]}><span>0{i+1}</span><div><h2>{x[0]}</h2><p>{x[1]}</p></div><b>EXPLORER ↗</b></Link>)}</section><section className="waitlist-inline"><h2>Recevoir les prochaines analyses.</h2><Link href="/contact" className="btn gold">REJOINDRE LA LISTE</Link></section></>}

export function PodcastPageV2(){const topics=["SCALING","LEADERSHIP","VENTE","AUTORITÉ","SYSTÈMES","HÉRITAGE"];return <><section className="podcast-stage"><div className="podcast-disc">TGC</div><div><p className="eyebrow">THE GAME CHANGER PODCAST</p><h2>Les conversations qui déplacent le niveau de jeu.</h2><p>Stratégies, systèmes et décisions des entrepreneurs qui construisent à une autre échelle. Les liens d’écoute seront raccordés dès leur transmission.</p></div></section><section className="podcast-topics podcast-links">{topics.map((x,i)=><Link href={`/podcast#${x.toLowerCase()}`} id={x.toLowerCase()} key={x}><span>0{i+1}</span><b>{x}</b><i>↗</i></Link>)}</section><section className="waitlist-inline"><h2>Ne manque pas le prochain épisode.</h2><Link href="/contact" className="btn gold">M’ABONNER</Link></section></>}

export function BookPageV2(){const books=[
  {title:"ALPHA LADDERS",subtitle:"Captain of Your Destiny — The Way of Alphas.",href:SITE_CONTENT.links.alphaLadders,img:"https://images-na.ssl-images-amazon.com/images/P/1989536565.01.LZZZZZZZ.jpg"},
  {title:"MASTERMIND",subtitle:"7 Ways to Get Into the Big League.",href:SITE_CONTENT.links.mastermind,img:"https://images-na.ssl-images-amazon.com/images/P/B081X9G3LQ.01.LZZZZZZZ.jpg"},
];return <><section className="book-thesis"><img src="/media/book-maintenant-ou-jamais.jpg" alt="Couverture Maintenant ou jamais"/><div><p className="eyebrow">LIVRE SIGNATURE</p><h2>Maintenant ou jamais.</h2><h3>Les 7 principes de l’ascension du conquérant.</h3><p>Un ouvrage sur la décision, l’élévation des standards et le passage de l’intention à une trajectoire assumée.</p><a href={SITE_CONTENT.links.maintenantOuJamais} target="_blank" rel="noreferrer" className="btn gold">COMMANDER SUR AMAZON</a></div></section><section className="other-books"><div><p className="eyebrow">BIBLIOGRAPHIE</p><h2>Deux autres ouvrages à découvrir.</h2></div><div className="book-cover-grid">{books.map((b,i)=><a href={b.href} target="_blank" rel="noreferrer" key={b.title}><img src={b.img} alt={`Couverture ${b.title}`}/><span>OUVRAGE 0{i+2}</span><h3>{b.title}</h3><p>{b.subtitle}</p><b>VOIR SUR AMAZON ↗</b></a>)}</div></section></>}
