"use client";

import Link from "next/link";
import { SITE_CONTENT } from "./site-content";
import { ClosingCalculator, RevenueCalculator } from "./special-pages";

type Step = { k: string; title: string; text: string };

const content: Record<string, {
  diagnosis: { eyebrow: string; title: string; text: string; image: string; bullets: string[] };
  contrast: { before: string[]; after: string[] };
  process: { eyebrow: string; title: string; steps: Step[] };
  assets: { eyebrow: string; title: string; items: Step[] };
  audience: { title: string; yes: string[]; no: string[] };
  faq: { q: string; a: string }[];
}> = {
  "methodologie-cdt": {
    diagnosis: { eyebrow: "LE PROBLÈME INVISIBLE", title: "Ton entreprise peut croître tout en devenant plus fragile.", text: "Plus de clients, plus d’outils et plus de collaborateurs ne règlent pas une architecture faible. Ils amplifient les dépendances, ralentissent les décisions et augmentent le coût du chaos.", image: "/media/portrait-window.jpg", bullets: ["Le fondateur reste le centre de toutes les décisions", "Les revenus progressent mais la marge et le temps diminuent", "Chaque nouveau client ajoute une nouvelle couche de complexité", "L’équipe exécute sans véritable système d’arbitrage"] },
    contrast: { before: ["Priorités concurrentes", "Offres dispersées", "Décisions répétitives", "Croissance dépendante du fondateur"], after: ["Une contrainte prioritaire", "Une offre phare", "Des règles de décision", "Un système qui accumule du levier"] },
    process: { eyebrow: "LES 5 MOUVEMENTS", title: "De l’ambition dispersée à l’exécution compressée.", steps: [{k:"01",title:"Diagnostiquer",text:"Identifier le goulot qui limite réellement la croissance."},{k:"02",title:"Éliminer",text:"Retirer les tâches, offres et décisions qui consomment sans multiplier."},{k:"03",title:"Architecturer",text:"Redessiner l’offre, la demande, la vente et la livraison comme un seul système."},{k:"04",title:"Activer",text:"Installer les cadences, indicateurs et responsabilités qui produisent le mouvement."},{k:"05",title:"Multiplier",text:"Transformer ce qui fonctionne en actifs reproductibles, délégables et mesurables."}] },
    assets: { eyebrow:"LE PROTOCOLE SOS", title:"Simplifier. Optimiser. Systématiser.", items:[{k:"S",title:"Simplifier",text:"Réduire le nombre de variables avant d’ajouter de la capacité."},{k:"O",title:"Optimiser",text:"Augmenter le rendement du levier déjà validé."},{k:"S",title:"Systématiser",text:"Documenter, automatiser et déléguer la performance."}] },
    audience: { title:"La CDT™ est conçue pour les entrepreneurs au plafond de leur propre succès.", yes:["Ton offre est validée mais la croissance reste irrégulière", "Tu es devenu le principal goulot de ton entreprise", "Tu veux augmenter revenu, contrôle et temps simultanément"], no:["Tu cherches une tactique miracle", "Tu refuses de supprimer les initiatives faibles", "Tu n’es pas prêt à mesurer et documenter ton exécution"] },
    faq:[{q:"La CDT™ est-elle une méthode de productivité ?",a:"Non. La productivité optimise l’individu. La CDT™ redessine le système économique et opérationnel autour de lui."},{q:"Faut-il déjà avoir une équipe ?",a:"Non. La méthode s’applique aux entrepreneurs solos comme aux micro-équipes, mais l’entreprise doit déjà avoir validé une offre."},{q:"Par où commencer ?",a:"Le CDT™ Scaling Swipe File permet d’identifier le goulot prioritaire avant toute transformation."}] },
  "services/the-shift": {
    diagnosis: { eyebrow:"LE PLAFOND", title:"Ce qui t’a permis d’atteindre six chiffres ne te permettra pas de franchir le prochain palier.", text:"Tu as une expertise, des clients et de la demande. Pourtant, le revenu reste irrégulier, la livraison dépend de toi et chaque croissance crée une nouvelle urgence. The Shift™ remplace ce modèle artisanal par une architecture de scaling complète.", image:"/media/red-chair-centered.jpg", bullets:["Une offre trop personnalisée pour être multipliée", "Un pipeline alimenté par des poussées d’énergie", "Une livraison qui absorbe toute la capacité", "Une équipe ou des outils sans système de pilotage"] },
    contrast: { before:["Vendre ton temps", "Mois inconsistants", "To-do infinie", "Expertise qui épuise"], after:["Vendre un système", "Pipeline piloté", "Business OS opérationnel", "Expertise qui se multiplie"] },
    process: { eyebrow:"12 SEMAINES · 3 PHASES", title:"Une transformation séquencée, pas une accumulation de contenu.", steps:[{k:"S1–4",title:"COMPRESS — Architecture",text:"Diagnostic CDT™, audit du temps, offre phare, pricing, modèle économique et Kill List."},{k:"S5–8",title:"ALIGN — Acquisition",text:"Message, canal principal, contenu d’autorité, pipeline, conversation de vente et scorecards."},{k:"S9–12",title:"MULTIPLY — Scaling",text:"Productisation, livraison, Business OS, automatisations, équipe et plan de scaling 12 mois."}] },
    assets: { eyebrow:"CE QUE TU CONSTRUIS", title:"Tu ne repars pas avec des notes. Tu repars avec une infrastructure.", items:[{k:"01",title:"Offre phare",text:"Promesse, structure, valeur, pricing et mécanisme propriétaire."},{k:"02",title:"Acquisition Stack",text:"Canal principal, contenus, capture, nurturing et pipeline."},{k:"03",title:"Sales System",text:"Diagnostic, scripts, suivi, objections et scorecard de conversion."},{k:"04",title:"Delivery System",text:"Parcours client, jalons, templates et contrôle qualité."},{k:"05",title:"Business OS",text:"Cadences, tableau de bord, priorités et règles de décision."},{k:"06",title:"Scale Plan",text:"Plan d’exécution documenté pour les 12 mois suivants."}] },
    audience: { title:"The Shift™ est pour le créatif brillant devenu prisonnier de son propre succès.", yes:["Entrepreneur, coach, consultant ou expert avec une offre déjà vendue", "Entreprise généralement entre 100 k$ et 500 k$ de chiffre d’affaires", "Solo ou micro-équipe prête à structurer le prochain palier", "Volonté d’exécuter chaque semaine pendant 12 semaines"], no:["Tu débutes sans offre validée", "Tu veux seulement davantage d’idées", "Tu refuses de concentrer ton modèle autour d’une offre phare", "Tu recherches une croissance sans discipline d’exécution"] },
    faq:[{q:"Est-ce du coaching de groupe classique ?",a:"Non. The Shift™ est un chantier d’architecture accompagné avec diagnostics, décisions, livrables et scorecards."},{q:"Le prix est-il affiché publiquement ?",a:"Non. L’investissement est présenté seulement après la préqualification et le diagnostic de fit."},{q:"Les résultats sont-ils garantis ?",a:"Aucun résultat universel n’est promis. Les conditions, l’exécution et le contexte de l’entreprise déterminent la performance."},{q:"Que se passe-t-il après les 12 semaines ?",a:"Tu disposes d’un Business OS et d’un Scale Plan 12 mois pour continuer l’exécution sans dépendance permanente."}] },
  "services/the-breakthrough": {
    diagnosis: { eyebrow:"LE GOULOT COMMERCIAL", title:"Tu n’as peut-être pas un problème de leads. Tu as un problème de conversion.", text:"Quand le positionnement, la qualification, la conversation et le suivi ne fonctionnent pas comme un seul système, chaque opportunité coûte trop cher. The Breakthrough™ transforme la vente en capacité pilotable.", image:"/media/speaking-close.jpg", bullets:["Des prospects intéressés qui ne prennent aucune décision", "Des appels menés à l’intuition", "Des objections découvertes trop tard", "Un suivi irrégulier et aucune lecture fiable du pipeline"] },
    contrast: { before:["Pitcher trop tôt", "Chasser les prospects", "Improviser les appels", "Mesurer seulement le revenu"], after:["Diagnostiquer avant de prescrire", "Créer une demande qualifiée", "Suivre une architecture de conversation", "Piloter chaque étape du pipeline"] },
    process: { eyebrow:"LE SYSTÈME DE VENTE", title:"De la demande à la décision.", steps:[{k:"01",title:"Positionnement",text:"Clarifier la valeur, le problème prioritaire et le coût de l’inaction."},{k:"02",title:"Qualification",text:"Filtrer le contexte, l’urgence, la capacité et le niveau de décision."},{k:"03",title:"Diagnostic",text:"Faire émerger l’écart entre la situation actuelle et le résultat désiré."},{k:"04",title:"Prescription",text:"Présenter l’offre comme la route logique, sans pression ni argumentaire générique."},{k:"05",title:"Suivi",text:"Installer une cadence et des règles qui empêchent les opportunités de disparaître."}] },
    assets: { eyebrow:"LIVRABLES", title:"Une machine de vente utilisable par toi — puis par ton équipe.", items:[{k:"01",title:"Message de vente",text:"Promesse, angles, preuves et réponses aux objections."},{k:"02",title:"Script diagnostic",text:"Questions, transitions, prescription et prochaines étapes."},{k:"03",title:"Pipeline",text:"Étapes, critères de passage, relances et responsabilités."},{k:"04",title:"Scorecards",text:"Taux de présence, qualification, proposition, closing et vélocité."},{k:"05",title:"Bibliothèque",text:"Courriels, suivis, réponses et scénarios de décision."},{k:"06",title:"Plan de performance",text:"Rituel hebdomadaire pour analyser et augmenter la conversion."}] },
    audience:{title:"Pour les entreprises qui ont déjà de la demande mais la convertissent en dessous de leur potentiel.",yes:["Tu réalises régulièrement des conversations de vente", "Ton offre possède déjà une valeur démontrée", "Tu veux rendre le closing mesurable et transmissible"],no:["Tu n’as aucune offre", "Tu cherches uniquement des phrases manipulatrices", "Tu refuses d’enregistrer et d’analyser tes appels"]},
    faq:[{q:"Est-ce uniquement pour les closers ?",a:"Non. Le programme s’adresse d’abord aux fondateurs et équipes commerciales qui vendent des offres de service à forte valeur."},{q:"Faut-il beaucoup de leads ?",a:"Non, mais il faut un volume minimal de conversations permettant de mesurer et d’améliorer le système."},{q:"Est-ce une formation autonome ?",a:"Non. L’architecture est adaptée à ton offre, ton marché et ton cycle de décision."}] },
  "services/the-dynasty-council": {
    diagnosis:{eyebrow:"AU-DELÀ DU REVENU",title:"À un certain niveau, le problème n’est plus l’information. C’est la qualité des décisions.",text:"The Dynasty Council™ est un conseil stratégique privé pour les entrepreneurs qui veulent orchestrer entreprise, capital, influence et héritage sans prendre seuls les décisions irréversibles.",image:"/media/red-chair-hero.png",bullets:["Trop peu d’espaces où parler sans façade", "Des décisions dont l’impact dépasse un trimestre", "Une croissance qui exige gouvernance et allocation du capital", "Le besoin de pairs capables de challenger le raisonnement"]},
    contrast:{before:["Réagir à l’urgence", "Accumuler des opportunités", "Décider seul", "Optimiser le revenu"],after:["Gouverner par intention", "Allouer le capital", "Décider avec un Conseil", "Construire patrimoine et influence"]},
    process:{eyebrow:"LES 4 SAISONS",title:"Une année structurée autour des décisions qui construisent une dynastie.",steps:[{k:"Q1",title:"Fondation",text:"Vision, gouvernance, structure, risques et allocation des ressources."},{k:"Q2",title:"Expansion",text:"Marchés, offres, partenariats, équipe et capacités de croissance."},{k:"Q3",title:"Capital",text:"Marge, actifs, investissements, patrimoine et options stratégiques."},{k:"Q4",title:"Héritage",text:"Influence, transmission, propriété intellectuelle et plan de la prochaine année."}]},
    assets:{eyebrow:"L’EXPÉRIENCE",title:"Un Conseil, pas une communauté de bruit.",items:[{k:"01",title:"Conseils stratégiques",text:"Sessions consacrées aux décisions structurantes des membres."},{k:"02",title:"Hot Seats",text:"Analyse directe d’un enjeu, de ses contraintes et de ses options."},{k:"03",title:"Mémos de décision",text:"Documentation des hypothèses, arbitrages et prochaines actions."},{k:"04",title:"Rencontres privées",text:"Expériences en petit comité conçues pour créer profondeur et confiance."},{k:"05",title:"Réseau de pairs",text:"Entrepreneurs sélectionnés selon leur maturité et leur contribution."},{k:"06",title:"Accès Jonas",text:"Regard externe pour les décisions dont le coût d’erreur est élevé."}]},
    audience:{title:"L’admission est volontairement restrictive.",yes:["Entreprise établie et enjeux de croissance réels", "Capacité à contribuer au niveau des autres membres", "Recherche de gouvernance, pas seulement de tactiques", "Disponibilité pour une implication sur douze mois"],no:["Recherche de réseautage transactionnel", "Besoin d’un programme pour débuter", "Refus de transparence ou de contribution", "Attente de solutions exécutées à ta place"]},
    faq:[{q:"Pourquoi une préqualification écrite ?",a:"Le niveau du Conseil dépend directement de la maturité, de la confidentialité et de la contribution de chaque membre."},{q:"Peut-on réserver directement un appel ?",a:"Non. Le dossier est d’abord étudié. Une conversation est proposée uniquement si l’adéquation est réelle."},{q:"Le prix est-il public ?",a:"Non. Les modalités sont communiquées au cours du processus de sélection."}] },
  conferences: {
    diagnosis:{eyebrow:"L’EXPÉRIENCE SCÈNE",title:"Une audience n’a pas besoin d’une heure de motivation. Elle a besoin d’une décision qu’elle ne pourra plus éviter.",text:"Chaque intervention combine narration, tension intellectuelle, modèles concrets et passage à l’action. Le contenu est adapté à l’audience, au contexte et au résultat attendu par l’organisation.",image:"/media/speaking-close.jpg",bullets:["Conférences d’ouverture ou de clôture", "Keynotes leadership et transformation", "Ateliers stratégiques pour dirigeants", "Panels, retraites et événements privés"]},
    contrast:{before:["Inspiration éphémère", "Concepts génériques", "Audience passive", "Aucune continuité"],after:["Décision mémorable", "Frameworks propriétaires", "Participation active", "Plan d’action exploitable"]},
    process:{eyebrow:"THÉMATIQUES",title:"Trois conférences pour changer le niveau de jeu.",steps:[{k:"01",title:"DÉCIDE OU SUBIS",text:"Leadership, responsabilité et puissance de décision dans l’incertitude."},{k:"02",title:"AJOUTER UN ZÉRO",text:"Les changements d’architecture nécessaires pour franchir un nouveau palier."},{k:"03",title:"COMPRESSER LE TEMPS",text:"Accélérer les résultats en supprimant la dispersion et en multipliant le levier."}]},
    assets:{eyebrow:"FORMATS",title:"Une intervention calibrée pour ton événement.",items:[{k:"20",title:"Keynote impact",text:"Un message court, intense et mémorable."},{k:"45",title:"Conférence signature",text:"Narration, modèles, interactions et conclusion d’action."},{k:"90",title:"Masterclass",text:"Approfondissement avec exercices et application."},{k:"½J",title:"Atelier stratégique",text:"Travail guidé sur un enjeu concret de l’organisation."},{k:"P",title:"Panel & modération",text:"Une conversation structurée qui fait émerger des décisions utiles."},{k:"VIP",title:"Retraite privée",text:"Intervention confidentielle pour dirigeants et équipes de direction."}]},
    audience:{title:"Pour les organisations qui veulent provoquer un mouvement mesurable.",yes:["Événement entrepreneurial ou corporatif", "Leadership, vente, performance ou transformation", "Audience prête à être challengée"],no:["Recherche d’un discours générique", "Aucune clarté sur l’audience", "Intervention sans préparation ni objectif"]},
    faq:[{q:"Jonas intervient-il hors de Montréal ?",a:"Oui. Les interventions peuvent être réalisées au Canada et à l’international, en présentiel ou à distance."},{q:"Le contenu est-il personnalisé ?",a:"Oui. Un briefing permet d’aligner le message, les exemples et le niveau d’interaction sur l’audience."},{q:"Comment obtenir une proposition ?",a:"Le formulaire événement recueille la date, le lieu, l’audience, le format et le budget afin de préparer une réponse adaptée."}] },
};

export function DeepPage({ slug }: { slug: string }) {
  const d = content[slug];
  if (!d) return null;
  const offer = slug === "services/the-shift" ? {label:"POSTULER À THE SHIFT™",href:SITE_CONTENT.links.shiftApplication} : slug === "services/the-breakthrough" ? {label:"REJOINDRE THE BREAKTHROUGH™",href:SITE_CONTENT.links.breakthroughApplication} : slug === "services/the-dynasty-council" ? {label:"POSTULER AU DYNASTY COUNCIL™",href:SITE_CONTENT.links.councilApplication} : slug === "conferences" ? {label:"INVITER JONAS",href:SITE_CONTENT.links.speakingApplication} : {label:"RECEVOIR LE SWIPE FILE",href:SITE_CONTENT.links.swipeFile};
  const faqExtras=[{q:"Quel est le meilleur premier pas ?",a:slug==="methodologie-cdt"?"Télécharge le CDT™ Scaling Swipe File pour identifier le goulot qui mérite d’être traité en premier.":"Commence par la candidature afin de vérifier l’adéquation entre ton contexte, ton urgence et le parcours."},{q:"Combien de temps faut-il prévoir chaque semaine ?",a:"Le rythme dépend du parcours, mais l’accompagnement exige une implication régulière dans les décisions, l’installation des actifs et la mesure de l’exécution."},{q:"Puis-je intégrer le parcours avec une petite équipe ?",a:"Oui. Les systèmes sont construits pour un fondateur solo ou une micro-équipe, à condition que l’offre soit déjà validée."}];
  const faqs=[...d.faq,...faqExtras.filter(x=>!d.faq.some(y=>y.q===x.q))].slice(0,Math.max(5,d.faq.length));
  return <>
    <section className="deep-diagnosis"><div><p className="eyebrow">{d.diagnosis.eyebrow}</p><h2>{d.diagnosis.title}</h2><p>{d.diagnosis.text}</p><ul>{d.diagnosis.bullets.map(x=><li key={x}>{x}</li>)}</ul></div><img src={d.diagnosis.image} alt="Jonas Diop"/></section>
    <section className="deep-contrast"><div><p className="eyebrow">AVANT</p>{d.contrast.before.map(x=><p key={x}>× {x}</p>)}</div><span>→</span><div><p className="eyebrow">APRÈS</p>{d.contrast.after.map(x=><p key={x}>✓ {x}</p>)}</div></section>
    <OfferCTA offer={offer} compact/>
    <section className="deep-process"><p className="eyebrow">{d.process.eyebrow}</p><h2>{d.process.title}</h2><div>{d.process.steps.map(s=><article key={s.k}><b>{s.k}</b><h3>{s.title}</h3><p>{s.text}</p></article>)}</div></section>
    <section className="deep-assets"><p className="eyebrow">{d.assets.eyebrow}</p><h2>{d.assets.title}</h2><div>{d.assets.items.map(s=><article key={s.k+s.title}><span>{s.k}</span><h3>{s.title}</h3><p>{s.text}</p></article>)}</div></section>
    {slug === "services/the-shift" && <RevenueCalculator/>}
    {slug === "services/the-breakthrough" && <ClosingCalculator/>}
    {slug === "conferences" && <section className="photo-proof"><img src="/media/speaking-audience.jpg" alt="Jonas Diop devant une audience"/><img src="/media/audience-hands.jpg" alt="Audience participant à une conférence de Jonas Diop"/><div><p className="eyebrow">CONFÉRENCIER · MONTRÉAL · INTERNATIONAL</p><h2>De la scène à la décision.</h2><p>Des centaines de participants réunis autour d’un même objectif : repartir avec une nouvelle lecture de leur responsabilité, de leur entreprise et de leur potentiel d’action.</p></div></section>}
    <section className="deep-fit"><h2>{d.audience.title}</h2><div><article><b>C’EST POUR TOI SI</b>{d.audience.yes.map(x=><p key={x}>✓ {x}</p>)}</article><article><b>CE N’EST PAS POUR TOI SI</b>{d.audience.no.map(x=><p key={x}>× {x}</p>)}</article></div></section>
    <OfferCTA offer={offer} compact/>
    <section className="deep-faq"><p className="eyebrow">QUESTIONS FRÉQUENTES</p><h2>Décider avec clarté.</h2>{faqs.map(x=><details key={x.q}><summary>{x.q}<span>+</span></summary><p>{x.a}</p></details>)}</section>
    <section className="deep-cta"><p className="eyebrow">LE PROCHAIN MOUVEMENT</p><h2>Une nouvelle ambition exige<br/><em>une nouvelle architecture.</em></h2><Link href={offer.href} className="btn gold">{offer.label}</Link></section>
  </>;
}

function OfferCTA({offer,compact=false}:{offer:{label:string;href:string},compact?:boolean}){return <section className={compact?"offer-cta compact":"offer-cta"}><p>PRÊT À CONSTRUIRE LE PROCHAIN MOUVEMENT ?</p><Link href={offer.href} className="btn gold">{offer.label}</Link></section>}
