"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { SITE_CONTENT } from "./site-content";
import { ResultsPageV2, ServicesPageV2 } from "./v2-pages";
import { ArticlesPageV2, BookPageV2, PodcastPageV2 } from "./content-enhancements";

export const SPECIAL_SLUGS = new Set([
  "services", "outils", "resultats", "a-propos", "ressources", "articles", "livre", "podcast", "evenements", "evenements/bootcamps", "evenements/masterclass", "evenements/retraites", "contact", "faq",
  "evenements/bootcamps/an-army-of-one", "evenements/bootcamps/the-edge", "evenements/bootcamps/the-activation",
]);

export function SpecialPage({ slug }: { slug: string }) {
  if (slug === "services") return <ServicesPageV2/>;
  if (slug === "outils") return <ToolsPage/>;
  if (slug === "resultats") return <ResultsPageV2/>;
  if (slug === "a-propos") return <AboutPage/>;
  if (slug === "ressources") return <ResourcesPage/>;
  if (slug === "articles") return <ArticlesPageV2/>;
  if (slug === "livre") return <BookPageV2/>;
  if (slug === "podcast") return <PodcastPageV2/>;
  if (slug === "evenements") return <EventsHub/>;
  if (slug === "evenements/bootcamps") return <BootcampsPage/>;
  if (slug === "evenements/masterclass") return <EventDetail kind="MASTERCLASS"/>;
  if (slug === "evenements/retraites") return <EventDetail kind="RETRAITES"/>;
  if (slug.startsWith("evenements/bootcamps/")) return <BootcampPage slug={slug}/>;
  if (slug === "contact") return <ContactPage/>;
  if (slug === "faq") return <FAQPage/>;
  return null;
}

function ServicesPage(){return <><section className="service-selector"><p className="eyebrow">QUEL EST TON GOULOT ?</p><h2>Une seule route doit être prioritaire.</h2><div>{[["01","SCALING","Ton entreprise dépend trop de toi.","THE SHIFT™","/services/the-shift"],["02","VENTE","Ta demande ne se transforme pas assez en revenu.","THE BREAKTHROUGH™","/services/the-breakthrough"],["03","GOUVERNANCE","Tes décisions dépassent le cadre d’un programme.","THE DYNASTY COUNCIL™","/services/the-dynasty-council"],["04","LEVIER TACTIQUE","Tu dois installer rapidement une capacité précise.","BOOTCAMPS","/evenements/bootcamps"]].map(x=><Link href={x[4]} key={x[0]}><span>{x[0]}</span><small>{x[1]}</small><p>{x[2]}</p><h3>{x[3]}</h3><b>EXPLORER ↗</b></Link>)}</div></section><section className="service-compare"><h2>Comparer les parcours.</h2><div className="compare-table"><p><b>PARCOURS</b><b>PROBLÈME</b><b>HORIZON</b><b>ACCÈS</b></p><p><span>The Shift™</span><span>Architecture globale de scaling</span><span>12 semaines</span><span>Game Changer Call</span></p><p><span>The Breakthrough™</span><span>Positionnement, pipeline et conversion</span><span>8–12 semaines</span><span>Game Changer Call</span></p><p><span>The Dynasty Council™</span><span>Gouvernance, capital et héritage</span><span>12 mois</span><span>Préqualification écrite</span></p><p><span>Bootcamps</span><span>Levier tactique ciblé</span><span>3 jours</span><span>Liste prioritaire</span></p></div></section><section className="service-process"><p className="eyebrow">LE PROCESSUS</p><div>{[["01","DIAGNOSTIC","Comprendre le contexte et le véritable goulot."],["02","ORIENTATION","Choisir le parcours adapté — ou aucune offre si le fit n’existe pas."],["03","ARCHITECTURE","Définir le système, les livrables et les indicateurs."],["04","EXÉCUTION","Installer, mesurer, corriger et documenter."]].map(x=><article key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section></>}

function ToolsPage(){return <>
  <section className="tool-intro"><p className="eyebrow">OUTILS DE DÉCISION</p><h2>Rendre visible ce que le chaos te coûte.</h2><p>Ces calculateurs ne remplacent pas un diagnostic. Ils transforment une intuition en ordre de grandeur afin de prioriser le prochain levier.</p></section>
  <TimeCalculator/>
  <RevenueCalculator/>
  <ClosingCalculator/>
  <section className="tool-cta"><h2>Le chiffre n’est que le symptôme.<br/><em>Trouvons le système qui le produit.</em></h2><Link href="/contact" className="btn gold">THE GAME CHANGER CALL</Link></section>
  </>}

function TimeCalculator(){
  const [hours,setHours]=useState(55),[rate,setRate]=useState(250),[low,setLow]=useState(45),[delegable,setDelegable]=useState(35);
  const r=useMemo(()=>{const wasted=hours*(low/100);const recoverable=wasted*(delegable/100);return{wasted,recoverable,annual:recoverable*rate*48}},[hours,rate,low,delegable]);
  return <section className="calculator dark"><div className="calculator-copy"><p className="eyebrow">CALCULATEUR 01</p><h2>Le coût du temps mal alloué.</h2><p>Mesure combien d’heures de fondateur sont absorbées par des activités qui pourraient être supprimées, automatisées ou déléguées.</p></div><div className="calc-panel">
    <Range label="Heures travaillées par semaine" value={hours} min={20} max={90} suffix=" h" set={setHours}/>
    <Range label="Valeur d’une heure stratégique" value={rate} min={50} max={1000} step={25} suffix=" $" set={setRate}/>
    <Range label="Part du temps à faible valeur" value={low} min={0} max={80} suffix=" %" set={setLow}/>
    <Range label="Part supprimable ou délégable" value={delegable} min={0} max={100} suffix=" %" set={setDelegable}/>
    <div className="calc-results"><div><b>{r.wasted.toFixed(1)} h</b><span>FAIBLE VALEUR / SEMAINE</span></div><div><b>{r.recoverable.toFixed(1)} h</b><span>RÉCUPÉRABLES / SEMAINE</span></div><div><b>{money(r.annual)}</b><span>CAPACITÉ ANNUELLE LIBÉRABLE</span></div></div>
  </div></section>}

function RevenueCalculator(){const [monthly,setMonthly]=useState(18000),[growth,setGrowth]=useState(35),[delay,setDelay]=useState(6);const loss=monthly*(growth/100)*delay;return <section className="calculator light"><div className="calculator-copy"><p className="eyebrow">CALCULATEUR 02</p><h2>Le coût de l’inaction.</h2><p>Estime le revenu potentiel non créé lorsque le principal goulot reste en place pendant plusieurs mois.</p></div><div className="calc-panel"><Range label="Chiffre d’affaires mensuel" value={monthly} min={3000} max={100000} step={1000} suffix=" $" set={setMonthly}/><Range label="Croissance potentielle bloquée" value={growth} min={5} max={100} step={5} suffix=" %" set={setGrowth}/><Range label="Mois avant d’agir" value={delay} min={1} max={24} suffix=" mois" set={setDelay}/><div className="single-result"><span>REVENU POTENTIEL NON CRÉÉ</span><b>{money(loss)}</b><small>Estimation indicative, non garantie.</small></div></div></section>}

function ClosingCalculator(){const [calls,setCalls]=useState(20),[ticket,setTicket]=useState(5000),[current,setCurrent]=useState(20),[target,setTarget]=useState(40);const gain=calls*ticket*((target-current)/100);return <section className="calculator dark"><div className="calculator-copy"><p className="eyebrow">CALCULATEUR 03</p><h2>Le levier du closing.</h2><p>Visualise l’impact mensuel d’une amélioration du taux de conversion sans générer un seul lead supplémentaire.</p></div><div className="calc-panel"><Range label="Appels qualifiés par mois" value={calls} min={1} max={100} suffix="" set={setCalls}/><Range label="Valeur moyenne d’une vente" value={ticket} min={500} max={30000} step={500} suffix=" $" set={setTicket}/><Range label="Taux actuel" value={current} min={5} max={80} step={5} suffix=" %" set={setCurrent}/><Range label="Taux cible" value={target} min={5} max={90} step={5} suffix=" %" set={setTarget}/><div className="single-result"><span>REVENU MENSUEL ADDITIONNEL POTENTIEL</span><b>{money(gain)}</b><small>Estimation indicative, non garantie.</small></div></div></section>}

function Range({label,value,min,max,step=1,suffix,set}:{label:string,value:number,min:number,max:number,step?:number,suffix:string,set:(n:number)=>void}){return <label className="range"><span>{label}<b>{value.toLocaleString("fr-CA")}{suffix}</b></span><input type="range" min={min} max={max} step={step} value={value} onChange={e=>set(+e.target.value)}/></label>}
function money(n:number){return new Intl.NumberFormat("fr-CA",{style:"currency",currency:"CAD",maximumFractionDigits:0}).format(n)}

export { TimeCalculator, RevenueCalculator, ClosingCalculator };

function ResultsPage(){return <>
  <section className="proof-standard"><div><p className="eyebrow">STANDARD DE PREUVE</p><h2>Un résultat sans contexte n’est pas une étude de cas.</h2></div><p>Chaque cas publié doit préciser la situation de départ, le goulot, l’intervention, la durée, le résultat et les conditions d’exécution. Aucun chiffre public ne sera utilisé sans source interne vérifiable.</p></section>
  <section className="case-placeholder"><p className="eyebrow">ÉTUDES DE CAS EN PRÉPARATION</p><h2>Les résultats réels seront publiés avec leurs preuves.</h2><div>{["SITUATION INITIALE","ARCHITECTURE INSTALLÉE","RÉSULTATS MESURÉS","DURÉE & CONDITIONS"].map((x,i)=><article key={x}><span>0{i+1}</span><h3>{x}</h3><p>Contenu à compléter avec le client, ses données et son autorisation écrite.</p></article>)}</div></section>
  <section className="results-evidence"><img src="/media/speaking-wide.jpg" alt="Jonas Diop devant une audience"/><div><p className="eyebrow">IMPACT DOCUMENTÉ</p><h2>270+ entrepreneurs accompagnés.</h2><p>La prochaine étape consiste à transformer cette expérience en bibliothèque de preuves : entrevues, captures, données avant/après et témoignages contextualisés.</p><Link href="/contact" className="btn gold">PARLER DE MA SITUATION</Link></div></section>
  </>}

function AboutPage(){return <>
  <section className="about-story"><img src="/media/portrait-blue.jpg" alt="Jonas Diop"/><div><p className="eyebrow">L’HISTOIRE DERRIÈRE LA MÉTHODE</p><h2>Je n’ai pas construit la CDT™ pour travailler plus vite.</h2><p>Je l’ai construite pour arrêter de confondre mouvement et progression. Après plus de quinze ans en stratégie, développement d’affaires, vente et transformation, une conviction s’est imposée : la majorité des plafonds ne viennent pas d’un manque d’ambition, mais d’une architecture devenue trop faible pour la supporter.</p><p>Mon travail consiste à rendre cette architecture visible, à supprimer ce qui disperse et à installer les systèmes qui permettent à une entreprise de grandir sans détruire son fondateur.</p></div></section>
  <section className="beliefs"><p className="eyebrow">PRINCIPES</p><h2>Ce que je refuse.<br/><em>Ce que je construis.</em></h2><div>{[["01","LA COMPLEXITÉ COMME STATUT","La sophistication inutile est souvent une incapacité à choisir."],["02","LA CROISSANCE SANS CONTRÔLE","Plus de revenu ne vaut rien si chaque vente augmente la dépendance."],["03","LES TACTIQUES SANS SYSTÈME","Une tactique produit un pic. Un système accumule un avantage."],["04","L’AUTORITÉ SANS PREUVE","Les promesses doivent être reliées à des données, des contextes et des conditions."],["05","LE FONDATEUR-HÉROS","Le but n’est pas de devenir indispensable. Le but est de construire ce qui fonctionne sans héroïsme."]].map(x=><article key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
  <section className="author-continuity punchy"><img src="/media/jonas-red-glasses.jpg" alt="Jonas Diop, auteur et stratège"/><div><p className="eyebrow">AUTEUR · CONFÉRENCIER · ARCHITECTE</p><h2>Maintenant ou jamais.</h2><p>Une même conviction traverse le livre, la scène et les accompagnements : une décision assumée peut changer toute une trajectoire.</p><Link href="/livre" className="text-link">DÉCOUVRIR LES LIVRES <span>↗</span></Link></div></section>
  </>}

function ResourcesPage(){const cards=[["SWIPE FILE","Diagnostiquer ton principal goulot de scaling.","/cdt-scaling-swipe-file"],["OUTILS","Mesurer le coût du chaos, du temps et de la conversion.","/outils"],["PODCAST","Écouter les conversations qui déplacent le niveau de jeu.","/podcast"],["LIVRE","Rejoindre la liste prioritaire de The Game Changer.","/livre"],["ÉVÉNEMENTS","Passer de la compréhension à l’exécution.","/evenements"],["CONFÉRENCES","Inviter Jonas pour provoquer une décision collective.","/conferences"]];return <><section className="resource-manifesto"><p className="eyebrow">LE HUB THE GAME CHANGER</p><h2>Chaque contenu doit créer un actif.</h2><p>Pas de bibliothèque décorative. Chaque ressource doit aider à diagnostiquer, décider ou exécuter.</p></section><section className="resource-grid">{cards.map((c,i)=><Link href={c[2]} key={c[0]}><span>0{i+1}</span><h3>{c[0]}</h3><p>{c[1]}</p><b>EXPLORER ↗</b></Link>)}</section></>}

function ArticlesPage(){return <><section className="resource-manifesto"><p className="eyebrow">ARTICLES & NEWSLETTER</p><h2>Des analyses pour penser comme un architecte.</h2><p>Les articles réels seront synchronisés avec The Game Changer. Aucun faux article « bientôt disponible » ne sera affiché.</p></section><section className="article-categories">{[["SCALING & CROISSANCE","Franchir un palier sans multiplier la complexité."],["OFFRES & POSITIONNEMENT","Créer une valeur claire, rare et difficile à comparer."],["VENTE & CONVERSION","Transformer la demande en décisions mesurables."],["SYSTÈMES & LEVIER","Construire ce qui continue de produire après l’effort."],["LEADERSHIP & DYNASTIE","Décider, gouverner et construire au-delà du revenu."]].map((x,i)=><article key={x[0]}><span>0{i+1}</span><h2>{x[0]}</h2><p>{x[1]}</p></article>)}</section><Waitlist title="Recevoir les prochaines analyses de The Game Changer."/></>}

function BookPage(){return <><section className="book-thesis"><img src="/media/book-maintenant-ou-jamais.jpg" alt="Livre de Jonas Diop"/><div><p className="eyebrow">THE GAME CHANGER · EN PRÉPARATION</p><h2>Le problème n’est pas de jouer plus fort.</h2><h3>Le problème est de jouer avec les mauvaises règles.</h3><p>The Game Changer est un livre sur le scaling, la compression du temps et la transformation du fondateur en architecte.</p></div></section><section className="book-parts">{[["PARTIE I","LE PLAFOND","Pourquoi l’effort qui a construit ton entreprise devient sa prochaine limite."],["PARTIE II","LE SHIFT","Comment redessiner l’offre, la demande, la vente et l’exécution."],["PARTIE III","LE SYSTÈME","Comment transformer les résultats en capacités reproductibles."],["PARTIE IV","LA DYNASTIE","Comment construire au-delà du revenu : actifs, influence et héritage."]].map(x=><article key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</section><Waitlist title="Recevoir un extrait et l’annonce de lancement."/></>}

function PodcastPage(){return <><section className="podcast-stage"><div className="podcast-disc">TGC</div><div><p className="eyebrow">THE GAME CHANGER PODCAST</p><h2>Stratégies, systèmes et décisions des entrepreneurs qui changent les règles.</h2><p>La page publique des épisodes sera activée avec les épisodes réels, leurs descriptions, invités, plateformes et transcriptions. Aucun épisode fictif ne sera affiché.</p></div></section><section className="podcast-topics">{["SCALING","LEADERSHIP","VENTE","AUTORITÉ","SYSTÈMES","HÉRITAGE"].map((x,i)=><div key={x}><span>0{i+1}</span><b>{x}</b></div>)}</section><Waitlist title="Être averti du prochain épisode."/></>}

function EventsPage(){return <><section className="event-routes">{[["BOOTCAMPS","Trois jours pour installer un avantage tactique.","/evenements/bootcamps"],["MASTERCLASS","Approfondir un problème stratégique précis.","/evenements"],["RETRAITES","Prendre de la hauteur et décider de la prochaine phase.","/evenements"]].map((x,i)=><Link href={x[2]} key={x[0]}><span>0{i+1}</span><h2>{x[0]}</h2><p>{x[1]}</p><b>DÉCOUVRIR ↗</b></Link>)}</section><Waitlist title="Recevoir les prochaines dates en priorité."/></>}

const camps={
  "evenements/bootcamps/an-army-of-one":{name:"AN ARMY OF ONE™",promise:"Produire comme une équipe. Décider comme un CEO.",theme:"PRODUCTIVITÉ · IA · EXÉCUTION",image:"/section-bg/army-hero-katana.webp",days:[["JOUR 1","COMMAND","Éliminer, prioriser et reprendre le contrôle de l’attention."],["JOUR 2","AUGMENT","Construire une stack IA autour de tes flux de travail réels."],["JOUR 3","SYSTEMIZE","Installer ton système personnel d’exécution et de mesure."]]},
  "evenements/bootcamps/the-edge":{name:"THE EDGE™",promise:"Devenir impossible à ignorer dans ton marché.",theme:"POSITIONNEMENT · AUTORITÉ · PR",image:"/section-bg/trilogie-hero-braziers.webp",days:[["JOUR 1","POSITION","Clarifier la catégorie, le message et le point de vue propriétaire."],["JOUR 2","PROVE","Transformer l’expérience en preuves, actifs et autorité."],["JOUR 3","AMPLIFY","Installer la distribution, les relations et l’omniprésence."]]},
  "evenements/bootcamps/the-activation":{name:"THE ACTIVATION™",promise:"Sortir de l’inertie et remettre la puissance en mouvement.",theme:"ÉNERGIE · DÉCISION · PERFORMANCE",image:"/section-bg/activation-hero-kintsugi.webp",days:[["JOUR 1","CONFRONT","Identifier les histoires, compromis et évitements qui maintiennent le plafond."],["JOUR 2","DECIDE","Créer une nouvelle norme de décision et d’engagement."],["JOUR 3","ACTIVATE","Transformer l’intention en protocole d’exécution immédiat."]]}
} as const;

function BootcampsPage(){return <><section className="camp-grid">{Object.entries(camps).map(([url,c],i)=><Link href={`/${url}`} key={url} style={{backgroundImage:`linear-gradient(rgba(5,5,5,.45),#090909),url(${c.image})`}}><span>0{i+1}</span><small>{c.theme}</small><h2>{c.name}</h2><p>{c.promise}</p><b>EXPLORER ↗</b></Link>)}</section><section className="camp-comparison"><h2>Choisir le bon avantage.</h2><div><p><b>AN ARMY OF ONE™</b> si ton goulot est l’exécution.</p><p><b>THE EDGE™</b> si ton goulot est la visibilité et l’autorité.</p><p><b>THE ACTIVATION™</b> si ton goulot est l’énergie et la décision.</p></div></section><Waitlist title="Recevoir les prochaines dates."/></>}

function BootcampPage({slug}:{slug:string}){const c=camps[slug as keyof typeof camps];return <><section className="camp-detail"><p className="eyebrow">{c.theme}</p><h2>{c.promise}</h2><p>Une immersion tactique de trois jours conçue pour produire un changement visible et un système immédiatement utilisable.</p></section><section className="camp-days">{c.days.map(x=><article key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</section><section className="camp-deliver"><h2>Tu repars avec :</h2><div>{["Un diagnostic clair", "Un système documenté", "Des templates d’exécution", "Un plan de 30 jours", "Une scorecard", "Une nouvelle cadence"].map(x=><p key={x}>✓ {x}</p>)}</div></section><Waitlist title={`Rejoindre la liste prioritaire ${c.name}.`}/></>}

function ContactPage(){const [route,setRoute]=useState("scaling");return <><section className="contact-router"><p className="eyebrow">CHOISIS TON INTENTION</p><div>{[["scaling","SCALER MON ENTREPRISE","The Game Changer Call"],["conference","INVITER JONAS","Conférence ou atelier"],["media","PRESSE & PARTENARIAT","Média, podcast ou collaboration"]].map(x=><button className={route===x[0]?"active":""} onClick={()=>setRoute(x[0])} key={x[0]}><b>{x[1]}</b><span>{x[2]}</span></button>)}</div></section><section className="qualification"><div><h2>{route==="scaling"?"The Game Changer Call":route==="conference"?"Soumettre un événement":"Présenter une collaboration"}</h2><p>{route==="scaling"?"Ce formulaire vérifie le fit. Il ne s’agit pas d’une séance de coaching gratuite.":"Donne suffisamment de contexte pour recevoir une réponse utile."}</p></div><form onSubmit={e=>e.preventDefault()}><input required placeholder="Nom complet"/><input required type="email" placeholder="Courriel"/><input placeholder="Entreprise / organisation"/><input placeholder={route==="scaling"?"Chiffre d’affaires annuel":"Date et lieu"}/><textarea required placeholder={route==="scaling"?"Quel est ton principal goulot de croissance ?":"Décris la demande, l’audience et le résultat attendu."}/><button className="btn gold">SOUMETTRE MA DEMANDE</button><small>Le calendrier est présenté uniquement après qualification.</small></form></section></>}

function FAQPage(){const groups=[
  ["THE GAME CHANGER CALL",[["Est-ce un appel de coaching gratuit ?","Non. Il s’agit d’un diagnostic de fit destiné à comprendre le contexte, le goulot, l’urgence et la pertinence d’un accompagnement."],["Qui devrait réserver ?","Les entrepreneurs possédant déjà une offre validée et confrontés à un plafond de croissance, de vente ou d’organisation."],["Le calendrier est-il accessible directement ?","Il est présenté après la préqualification afin d’éviter les conversations sans contexte ni adéquation."]]],
  ["ACCOMPAGNEMENTS",[["Quelle différence entre The Shift™ et The Breakthrough™ ?","The Shift™ restructure l’ensemble du système de croissance. The Breakthrough™ se concentre sur le positionnement, le pipeline et la conversion."],["Comment intégrer The Dynasty Council™ ?","La candidature écrite est étudiée avant toute invitation à une conversation privée."],["Les programmes sont-ils adaptés aux débutants ?","Les accompagnements principaux s’adressent à des entrepreneurs ayant déjà validé une offre. Les bootcamps couvrent des leviers tactiques plus ciblés."]]],
  ["INVESTISSEMENT",[["Pourquoi les prix ne sont-ils pas affichés ?","L’investissement dépend du parcours et n’est communiqué qu’après vérification du fit. Aucun prix des trois programmes principaux n’est affiché publiquement."],["Existe-t-il des facilités de paiement ?","Les modalités disponibles sont expliquées uniquement dans le cadre du processus de candidature."]]],
  ["RÉSULTATS",[["Les résultats sont-ils garantis ?","Non. Les résultats dépendent du contexte, du marché, de la qualité de l’offre et de l’exécution. Les garanties éventuelles comportent des conditions précises."],["Comment les études de cas sont-elles validées ?","Chaque cas doit présenter le contexte, l’intervention, la durée, les résultats et les preuves disponibles avec l’autorisation du client."]]],
  ["LOGISTIQUE",[["Les accompagnements sont-ils à distance ?","La majorité peut être réalisée à distance. Certains événements et expériences privées peuvent avoir lieu à Montréal ou ailleurs."],["Y a-t-il des replays ?","La disponibilité des replays dépend du format. Les détails sont précisés avant l’inscription."],["Comment contacter Jonas pour une conférence ?","Utilise la route « Inviter Jonas » sur la page Contact avec la date, le lieu, l’audience, le format et le budget."]]],
];return <section className="faq-groups">{groups.map(g=><div key={g[0] as string}><h2>{g[0]}</h2>{(g[1] as string[][]).map(x=><details key={x[0]}><summary>{x[0]}<span>+</span></summary><p>{x[1]}</p></details>)}</div>)}</section>}

function Waitlist({title}:{title:string}){return <section className="waitlist"><div><p className="eyebrow">LISTE PRIORITAIRE</p><h2>{title}</h2></div><form onSubmit={e=>e.preventDefault()}><input required placeholder="Prénom"/><input required type="email" placeholder="Courriel"/><button className="btn gold">M’INSCRIRE</button></form></section>}

function BookLibrary(){const books=[["MAINTENANT OU JAMAIS","Les 7 principes de l’ascension du conquérant.",SITE_CONTENT.links.maintenantOuJamais],["ALPHA LADDERS","Captain Your Destiny — The Way of Alphas.",SITE_CONTENT.links.alphaLadders],["MASTERMIND","7 Ways to Get Into the Big League.",SITE_CONTENT.links.mastermind]];return <><section className="book-thesis"><img src="/media/book-maintenant-ou-jamais.jpg" alt="Maintenant ou jamais de Jonas Diop"/><div><p className="eyebrow">LIVRE SIGNATURE</p><h2>Maintenant ou jamais.</h2><h3>Les 7 principes de l’ascension du conquérant.</h3><p>Un ouvrage sur la décision, l’élévation des standards et le passage de l’intention à une trajectoire assumée.</p><a href={SITE_CONTENT.links.maintenantOuJamais} target="_blank" rel="noreferrer" className="btn gold">COMMANDER SUR AMAZON</a></div></section><section className="book-parts book-library">{books.map((x,i)=><article key={x[0]}><span>OUVRAGE 0{i+1}</span><h3>{x[0]}</h3><p>{x[1]}</p><a href={x[2]} target="_blank" rel="noreferrer" className="text-link">VOIR SUR AMAZON ↗</a></article>)}</section></>}

function EventsHub(){return <><section className="event-routes">{[["BOOTCAMPS","Trois jours pour installer un avantage tactique.","/evenements/bootcamps"],["MASTERCLASS","Approfondir un problème stratégique précis.","/evenements/masterclass"],["RETRAITES","Prendre de la hauteur et décider de la prochaine phase.","/evenements/retraites"]].map((x,i)=><Link href={x[2]} key={x[0]}><span>0{i+1}</span><h2>{x[0]}</h2><p>{x[1]}</p><b>DÉCOUVRIR ↗</b></Link>)}</section><Waitlist title="Recevoir les prochaines dates en priorité."/></>}

function EventDetail({kind}:{kind:"MASTERCLASS"|"RETRAITES"}){const retreat=kind==="RETRAITES";const items=retreat?[["01","CLARTÉ","Sortir de l’opérationnel pour voir la prochaine phase."],["02","GOUVERNANCE","Arbitrer capital, équipe, risques et priorités."],["03","DÉCISIONS","Repartir avec un plan précis et une nouvelle cadence."]]:[["01","DIAGNOSTIC","Isoler un problème stratégique précis."],["02","FRAMEWORK","Comprendre le modèle et ses décisions critiques."],["03","APPLICATION","Construire l’actif directement pendant la session."]];return <><section className="camp-detail"><p className="eyebrow">EXPÉRIENCE · {kind}</p><h2>{retreat?"Prendre de la hauteur pour décider sans le bruit.":"Une question. Une architecture. Un actif utilisable."}</h2><p>{retreat?"Une expérience en comité restreint pour orchestrer entreprise, capital et leadership.":"Des sessions intensives consacrées à un levier précis, avec application guidée."}</p></section><section className="camp-days">{items.map(x=><article key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</section><Waitlist title={`Recevoir les prochaines dates ${kind.toLowerCase()}.`}/></>}
